git:
  depth: false

env:
  - HUGO_VERSION="0.49.2"
  - HUGO_VERSION="0.50"
  - HUGO_VERSION="0.51"
  - HUGO_VERSION="0.52"
  - HUGO_VERSION="0.53"
  - HUGO_VERSION="0.54.0"
  - HUGO_VERSION="0.55.0"
  - HUGO_VERSION="0.56.0"
  - HUGO_VERSION="0.57.0"
  - HUGO_VERSION="0.58.0"
  - HUGO_VERSION="0.59.0"
  - HUGO_VERSION="0.60.0"
  - HUGO_VERSION="0.61.0"
  - HUGO_VERSION="0.62.0"
  - HUGO_VERSION="0.63.0"
  - HUGO_VERSION="0.64.0"
  - HUGO_VERSION="0.65.0"
  - HUGO_VERSION="0.66.0"
  - HUGO_VERSION="0.67.0"

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
  - npm install autoprefixer postcss-cli
  - mv hugo ~/bin/
  - gem install html-proofer

script:
  - cd exampleSite
  - HUGO_THEME=hugo-theme-sam hugo --themesDir ../.. -v
  - htmlproofer public --check-html --disable-external
